### PR TITLE
fix Python 3

### PR DESCRIPTION
**Pull request by speleo3**
https://sourceforge.net/p/pmw/patches/7/

### CODE REVIEW

**Comment by mcs07** [comment]
Thanks! Just to double check, is it fine that this patch is also applied under python 2? Or should it be restricted to python 3 with:

    patches:
      - Pmw_2_0_1-py36.patch  # [py>=3]

**Comment by speleo3** [comment]
The patch works fine with Python 2, no need to restrict it

**Comment by mcs07** [comment]
Oops, I forgot that the build number needs to incremented. I can do that in a new PR.

Thanks for this. Any chance of getting the open source PyMOL onto conda-forge? :-)

**Comment by speleo3** [comment]
https://anaconda.org/schrodinger/pymol plays very nice with conda-forge! Having Open-Source PyMOL on conda-forge in addition would be more [free beer](https://www.gnu.org/philosophy/free-sw.en.html) than we can handle at the moment with our commercial open source business model :-)

**Pull request merged**
